import * as pdfjsLib from "https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.min.mjs";
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdn.jsdelivr.net/npm/pdfjs-dist@6.3.289/build/pdf.worker.min.mjs";
const params=new URLSearchParams(window.location.search);const deckId=params.get("id")||"demo";
const canvas=document.getElementById("pdf-canvas"),ctx=canvas.getContext("2d"),stage=document.getElementById("stage"),message=document.getElementById("message");
const titleEl=document.getElementById("deck-title"),authorEl=document.getElementById("deck-author"),footerEl=document.getElementById("footer-text"),pageNumberInput=document.getElementById("page-number"),pageCountEl=document.getElementById("page-count"),openPdfEl=document.getElementById("open-pdf");
let pdf=null,currentPage=1,rendering=false,pendingPage=null;
async function loadManifest(){const r=await fetch("./presentations.json",{cache:"no-store"});if(!r.ok)throw new Error(`Не удалось загрузить presentations.json (${r.status})`);const m=await r.json();const d=m[deckId];if(!d)throw new Error(`Презентация с id="${deckId}" не найдена`);return d}
function setMetadata(d){titleEl.textContent=d.title||"BeamerDeck";authorEl.textContent=d.author||"";footerEl.textContent=d.footer||d.author||"Учебные материалы";document.title=`${d.title||"BeamerDeck"} — BeamerDeck`;openPdfEl.href=d.file}
async function renderPage(n){if(!pdf)return;if(rendering){pendingPage=n;return}rendering=true;currentPage=Math.max(1,Math.min(n,pdf.numPages));pageNumberInput.value=currentPage;try{const page=await pdf.getPage(currentPage);const base=page.getViewport({scale:1});const w=Math.max(stage.clientWidth-36,320),h=Math.max(stage.clientHeight-36,240);const scale=Math.min(w/base.width,h/base.height);const viewport=page.getViewport({scale});const out=window.devicePixelRatio||1;canvas.width=Math.floor(viewport.width*out);canvas.height=Math.floor(viewport.height*out);canvas.style.width=`${Math.floor(viewport.width)}px`;canvas.style.height=`${Math.floor(viewport.height)}px`;await page.render({canvasContext:ctx,viewport,transform:out!==1?[out,0,0,out,0,0]:null}).promise;message.classList.add("hidden")}catch(e){console.error(e);message.textContent=`Ошибка рендеринга: ${e.message}`;message.classList.remove("hidden")}finally{rendering=false;if(pendingPage!==null){const x=pendingPage;pendingPage=null;renderPage(x)}}}
async function init(){try{const d=await loadManifest();setMetadata(d);pdf=await pdfjsLib.getDocument({url:d.file}).promise;pageCountEl.textContent=pdf.numPages;pageNumberInput.max=pdf.numPages;await renderPage(1)}catch(e){console.error(e);message.textContent=`${e.message}. Проверь presentations.json и путь к PDF.`}}
document.getElementById("prev").onclick=()=>{if(currentPage>1)renderPage(currentPage-1)};document.getElementById("next").onclick=()=>{if(pdf&&currentPage<pdf.numPages)renderPage(currentPage+1)};document.getElementById("fit").onclick=()=>renderPage(currentPage);document.getElementById("fullscreen").onclick=async()=>{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()};pageNumberInput.onchange=()=>{const n=parseInt(pageNumberInput.value,10);if(Number.isFinite(n))renderPage(n)};
window.addEventListener("keydown",e=>{if(document.activeElement?.tagName?.toLowerCase()==="input")return;if(["ArrowRight","PageDown"," "].includes(e.key)){e.preventDefault();if(pdf&&currentPage<pdf.numPages)renderPage(currentPage+1)}if(["ArrowLeft","PageUp"].includes(e.key)){e.preventDefault();if(currentPage>1)renderPage(currentPage-1)}if(e.key==="Home")renderPage(1);if(e.key==="End"&&pdf)renderPage(pdf.numPages)});let timer=null;window.addEventListener("resize",()=>{clearTimeout(timer);timer=setTimeout(()=>renderPage(currentPage),120)});init();